<div class="profile persona ${steamprofile.onlineState}" href="/profile">
    <a class="profileLink" href="/profile"></a>

    <div class="profileAvatar ${steamprofile.onlineState}">
        <img src="${steamprofile.avatarIcon}">
    </div>
    <div>
        ${steamprofile.steamName}
        <br>
        <span>
            <span>
                ${steamprofile.stateMessage}
                <br>
            </span>
        </span>
    </div>
</div>